spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:exercise
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  liquibase:
    user: sa
    password:
    change-log: classpath:db/changelog/liquidbase-changelog.xml

    #logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
